export interface Gym {
        id: number,
        name: string,
        category: string,
        addressStreet: string,
        addressCity: string,
        addressState: string,
        addressZip: number,
        hours: string,
        phone: string,
        details: string,
        image: string,
        // owner: any,
        // equipmentList: any,
        // amenityList: any,
}